name: Rust

on:
  push:
    branches: [ "master", "workflow_test" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - run: git submodule update --init --force
    - run: cmake -S gruggers/src/grug_tests/ -B ./gruggers/src/grug_tests/build/ -G Ninja -DCMAKE_BUILD_TYPE=Release
    - run: cmake --build ./gruggers/src/grug_tests/build
    - run: cmake -S gruggers/src/grug_bench/ -B ./gruggers/src/grug_bench/build/ -G Ninja -DCMAKE_BUILD_TYPE=Release
    - run: cmake --build ./gruggers/src/grug_bench/build
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
